# Build  BISICLES abd run a regression test. Based on the basic workflow

name: build and test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ "main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # obtain dependencies, BISICLES and Chombo
  init:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # obtain the submodule sources
      - name: submodule init / update
        run: | 
          git submodule init
          git submodule update --remote

      # Runs a single command using the runners shell
      - name: top level list
        run: ls

      # Attempt to link the Make.defs files
      - name: specify Make.defs
        run: |
          ln -s $PWD/Make.defs.local.ubuntu Chombo/lib/mk/Make.defs.local
          ln -s Make.defs.ubuntu_22.4 bisicles-uob/code/mk/Make.defs.`uname -n`
          ls -l Chombo/lib/mk/Make.defs.local
          ls -l bisicles-uob/code/mk/Make.defs.`uname -n`

      #Install hdf5 etc
      - name: install dependencies
        run: | 
          sudo apt install gfortran csh mpi-default-bin mpi-default-dev 
          sudo apt install libhdf5-mpi-dev libhdf5-dev hdf5-tools 
          sudo apt install libnetcdff-dev libnetcdf-dev netcdf-bin nco
          sudo apt install python3 python3-dev libpython3-dev
          sudo apt install libfftw3-dev

      #build the serial. opt version
      - name: build serial opt bisicles
        run: |
           ls -l
           cd $GITHUB_WORKSPACE/bisicles-uob/code/exec2D/
           make -j4 all OPT=TRUE
           cd $GITHUB_WORKSPACE/bisicles-uob/code/filetools/
           make -j4 all OPT=TRUE

      - name: plot-cf test  serial opt bisicles
        run: |
           cd $GITHUB_WORKSPACE/bisicles-uob/code/regression/plot-cf
           ../../exec2D/driver2d.Linux.64.g++.gfortran.DEBUG.OPT.ex inputs.regression > sout
           grep HDF5NormTest sout

           
           
          
